#!/bin/bash

#Description: Tell the color of a fruit

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <fruit>" >&2
	exit 1
fi

fruit="$1"

case "$fruit" in
    apple)
        echo "red"
        ;;
    banana)
        echo "yellow"
        ;;
    kiwi)
	echo "green"
	;;
    *)
        echo "Usage: $0 Unknown fruit: $fruit" >&2
        exit 1
        ;;
esac
