apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkding
  name: linkding
  namespace: linkding
spec:
  replicas: 3
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - image: "sissbruecker/linkding:1.45.0-plus-alpine"
          name: linkding
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          env:
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-user
                  key: linkding-user
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-pwd
                  key: linkding-password
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data
